### ISSUE TITLE
Fresh installation failed

### ISSUE THREAD

**Issue by laymain** [Kunstmaan/KunstmaanBundlesStandardEdition#154]
Hi,

When I follow the first step of the installation guide, it fails with the following error:

```
  [Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]
  You have requested a non-existent parameter "sm*".

Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-install-cmd event terminated with an exception

  [RuntimeException]
  An error occurred when executing the ""cache:clear --no-warmup"" command.
```

**Comment by laymain** [comment]
I have found where this issue came from, I had special chars in my secret token including '%':

```yml
# This file is auto-generated during the composer install
parameters:
...
    secret: 'h)j%%s^1395cueqw^8irewts=bhag%sm*%v8!#j!q3=c5y(@@h'
...
```

Special chars in parameters.yml should be escaped '%' -> '%%'
